clgstoredebug/clgapp/urls.py
from django.urls import path
from . import views
app_name='clgapp'

urlpatterns = [

     path('',views.home,name="home"),
     path('register/',views.register,name="register"),
     path('login/',views.login,name="login"),
     path('student/', views.student, name="student"),



     path('add/',views.student_create_view,name="add"),

     path('ajax/load-courses/', views.load_courses, name='ajax_load_courses'),
     path('logout/', views.log_out, name="logout"),
]

clgstoredebug/clgstore/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('clgapp.urls')),
]

clgstoredebug/clgapp/models.py
from datetime import date
from django.forms.widgets import SelectDateWidget  # Correct

from django.contrib.admin import widgets
from django.db import models
from django import forms

from numpy.ma import extras


# Create your models here.
class department(models.Model):
    name=models.CharField(max_length=50)


    def __str__(self):
        return self.name

class course(models.Model):
    department=models.ForeignKey(department, on_delete=models.CASCADE)
    name=models.CharField(max_length=50)

    def __str__(self):
        return self.name


class purpose(models.Model):
    name=models.CharField(max_length=50)


    def __str__(self):
        return self.name


class material(models.Model):
    name=models.CharField(max_length=50)


    def __str__(self):
        return self.name

class student(models.Model):
    gender_choices=[
        ("m","male"),
        ("f","female")
    ]
    name=models.CharField(max_length=50)
    age = models.IntegerField()
    phone = models.IntegerField()
    birth_date = models.DateField()
    mailid = models.EmailField()
    address= models.CharField(max_length=50)
    gender=models.CharField(max_length=1,choices=gender_choices,default="m")
    department = models.ForeignKey(department,on_delete=models.SET_NULL,blank=True, null=True)
    course = models.ForeignKey(course,on_delete=models.SET_NULL,blank=True, null=True)
    purpose = models.ForeignKey(purpose,on_delete=models.SET_NULL,blank=True, null=True)
    material = models.ForeignKey(material,on_delete=models.SET_NULL,blank=True, null=True)
    def __str__(self):
        return self.name

clgstoredebug/clgapp/forms.py
from django import forms
from .models import student,course
class StudentCreationForm(forms.ModelForm):
    class Meta:
        model= student
        fields = "__all__"

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields['course'].queryset = course.objects.none()

            if 'department' in self.data:
                try:
                    department_id = int(self.data.get('department'))
                    self.fields['course'].queryset = course.objects.filter(department_id=department_id).order_by('name')
                except (ValueError, TypeError):
                    pass
            elif self.instance.pk:
                self.fields['course'].queryset = self.instance.department.course_set.order_by('name')

clgstoredebug/clgapp/views.py
from django.contrib import messages
from django.contrib.auth import logout
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.models import User, auth

from .forms import StudentCreationForm
from .models import student,course

def home(request):
    return render(request, 'home.html')

def register(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        confirm_password = request.POST.get('confirm_password')

        if password == confirm_password:
            if User.objects.filter(username=username).exists():
                messages.info(request, 'Username already exists')
                return redirect('clgapp:register')

            user = User.objects.create_user(username=username, password=password)
            user.save()

            messages.success(request, 'Registration successful. Please log in.')
            return redirect('clgapp:login')

        else:
            messages.error(request, 'Passwords do not match')
            return redirect('clgapp:register')

    return render(request, 'register.html')

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return redirect('clgapp:student')
        else:
            messages.error(request, 'Invalid credentials')
            return redirect('clgapp:login')

    return render(request, 'login.html')
def student(request):
    return render(request, 'student.html')
def add(request):
    return render(request, 'add.html')


def student_create_view(request):
    form = StudentCreationForm()
    if request.method=='POST':
        form=StudentCreationForm(request.POST)

    if form.is_valid():
        form.save()
        messages.success(request, 'Submission successful')
        return redirect('clgapp:add')
    return render(request, 'add.html', {'form': form})

def load_courses(request):
    department_id = request.GET.get('department_id')
    courses = course.objects.filter(department_id=department_id).all()
    return render(request, 'clgapp/courses.html', {'courses': courses})


def log_out(request):
    logout(request)
    return HttpResponse("logout successfully")

clgstoredebug/templates/add.html
<form method="POST" enctype="multipart/form-data"  id="studentForm" data-courses-url="{% url 'clgapp:ajax_load_courses' %}">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">

       <a class="btn btn-primary" href="{% url 'clgapp:logout' %}" role="button">Logout</a>
     <br>
       <a class="btn btn-secondary" href="{% url 'clgapp:home' %}">Home</a>

</form>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_department").change(function () {
        const url = $("#studentForm").attr("data-courses-url");
        const departmentId = $(this).val();

        $.ajax({
            url: url,
            data: {
                'department_id': departmentId
            },
            success: function (data) {
                $("#id_course").html(data);
            }
        });

    });
</script>

</body>
</html>

clgstoredebug/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

<body>
<!-- Image and text -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">COLLEGE STORE</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'clgapp:register' %}">Register</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'clgapp:login' %}">Login</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Department
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Computer_science">Computer Science</a>
          <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Commerce">Commerce</a>
          <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Medicine">Medicine</a>
          <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Science">Science</a>
            <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Physics">Physics</a>
            <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Literature">Literature</a>
        </div>
      </li>
    </ul>
  </div>
   <a class="btn btn-primary" href="{% url 'clgapp:login' %}" role="button">Login</a>
</nav>
<img src="static/img/schoool.jpg" alt="myimage" width="1400" height="650">
{% block body %}
{% endblock %}
</body>
</html>

clgstoredebug/templates/courses.html
<option value="">---------</option>
{% for course in courses %}
<option value="{{ course.pk }}">{{ course.name }}</option>
{% endfor %}

clgstoredebug/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

   <title>school</title>
  </head>
  <body style="background-image:url('{% static 'img/sc.png' %}');background-repeat:no-repeat;background-size:100%;">




  </body>
</html>
{% endblock %}

clgstoredebug/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>login</title>
</head>
<body>
<form action="" method="post">
  {% csrf_token %}
  <input type="text" name="username" placeholder="enter your username"><br>
  <input type="password" name="password" placeholder="enter your password"><br>
  <input type="submit">
    <div class="text">
        <h3> <a href="">Login</a></h3>
      </div>
    <div class="text">
        <h3>create an account <a href="{% url 'clgapp:register' %}">Register now</a></h3>
      </div>
</form>
</body>
</html>

clgstoredebug/templates/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

clgstoredebug/templates/register.html
{% load static %}
<!DOCTYPE html>

<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Registration or Sign Up </title>

    <link rel="stylesheet" href="{% static 'style.css' %}">
  </head>
<body>
  <div class="wrapper">
    <h2>Registration</h2>
   <form method="POST" action="">
      {% csrf_token %}
      <div class="input-box">
        <input type="text" placeholder="Enter your username"  name="username">
      </div>

      <div class="input-box">
        <input type="password" placeholder="Create password"  name="password">
      </div>
      <div class="input-box">
        <input type="password" placeholder="Confirm password"  name="confirm_password">
      </div>

      <div class="input-box button">
        <input type="Submit">
      </div>
      <div class="text">
        <h3>Already have an account? <a href="{% url 'clgapp:login' %}">Login now</a></h3>
      </div>
    </form>
  </div>
</body>
</html>

clgstoredebug/templates/student.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Student Submission Form</title>
</head>
<body>
<h1>Student Submission Form</h1>

<a class="btn btn-primary" href="{% url 'clgapp:add' %}" role="button">Form</a>

</body>
</html>